### ISSUE TITLE
Pod Fails - CrashLoopBackOff

### ISSUE THREAD

**Issue by Immanuel-Daniel** [deis/example-php#10]
Pod creation fails with logs, 

2016/08/29 12:32:35 RequestError: send request failed
caused by: Put http://10.3.0.177:9000/git: dial tcp 10.3.0.177:9000: i/o timeout

Please tell me if I'm missing anything here.

**Comment by Joshua-Anderson** [comment]
Sorry you're having issues.

I suspect that this issue isn't with the application itself, but with deis workflow or kubernetes.

What version of deis workflow are you using?
Do any of the other example apps work?

**Comment by mboersma** [comment]
@Immanuel-Daniel we suspect this is a k8s setup issue since no similar bug has been reported. I'm going to close it, but if you're still running into this and think it's a Deis Workflow issue, please provide us with more troubleshooting details.
