### ISSUE TITLE
Git Push - Issue

### ISSUE THREAD

**Issue by Immanuel-Daniel** [deis/example-php#8]
On a git push, I'm alerted with the below error. By referring to related issues and fixes I've updated composer to use the latest version of build-pack, doesn't seem to fix either. Please help to resolve,

Counting objects: 231, done.
Delta compression using up to 24 threads.
Compressing objects: 100% (166/166), done.
Writing objects: 100% (231/231), 371.84 KiB | 0 bytes/s, done.
Total 231 (delta 55), reused 231 (delta 55)
Starting build... but first, coffee!
-----> PHP app detected
-----> Bootstrapping...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
remote: 2016/08/22 07:17:51 Error running git receive hook [Build pod exited with code 2, stopping build.]
To ssh://git@deis-builder.10.3.0.22.nip.io:2222/decent-uptowner.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis-builder.10.3.0.22.nip.io:2222/decent-uptowner.git'

**Comment by Joshua-Anderson** [comment]
This issue has come up in deis/workflow#429

Basically, the default php buildback shipped with workflow `v2.3.0` is broken. However, you can update the buildpack on a per-app basis by running `deis config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php.git`

This has been fixed in workflow `v2.4.0` and later.

**Comment by monaka** [comment]
@Joshua-Anderson Seems degraded. My Deis is workflow-v2.11.0  

The workaround is to execute `deis config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php`

```
$ git clone git@github.com:deis/example-php.git
Cloning into 'example-php'...
remote: Counting objects: 239, done.
remote: Total 239 (delta 0), reused 0 (delta 0), pack-reused 239
Receiving objects: 100% (239/239), 375.15 KiB | 278.00 KiB/s, done.
Resolving deltas: 100% (57/57), done.
Checking connectivity... done.

$ cd example-php/

$ ls
LICENSE  Procfile  README.md  composer.json  composer.lock  web

$ deis create example-php
Creating Application... done, created example-php
Git remote deis successfully created for app example-php.

$ git push deis master
Counting objects: 239, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (172/172), done.
Writing objects: 100% (239/239), 375.14 KiB | 0 bytes/s, done.
Total 239 (delta 57), reused 239 (delta 57)
remote: Resolving deltas: 100% (57/57), done.
Starting build... but first, coffee!
-----> Restoring cache...
       No cache file found. If this is the first deploy, it will be created now.
-----> PHP app detected
-----> Bootstrapping...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
remote: 2017/02/23 02:37:07 Error running git receive hook [Build pod exited with code 2, stopping build.]
To ssh://git@deis-builder.{snip}.com:2222/example-php.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis-builder.{snip}.com:2222/example-php.git'
```

**Comment by Joshua-Anderson** [comment]
@monaka seems like the same issue came up again where heroku moved binaries. @mboersma should update the heroku buildpack for the next workflow release. Until then, there isn't much that can be done to fix it :(

**Comment by mboersma** [comment]
> should update the heroku buildpack for the next workflow release

See deis/slugbuilder#130 and deis/slugbuilder#131.
